version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install -g htmlhint # Install HTMLHint for HTML linting
  pre_build:
    commands:
      - echo Checking the existence of index.html...
      - test -f index.html # This will fail if index.html does not exist
  build:
    commands:
      - echo Linting HTML...
      - htmlhint index.html # Perform HTML linting
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
  discard-paths: yes